-- MySQL Script generated by MySQL Workbench
-- 2019-12-18 12:14:34 +0530
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hrm_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hrm_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hrm_db` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema rr
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rr` DEFAULT CHARACTER SET latin1 ;
USE `hrm_db` ;

-- -----------------------------------------------------
-- Table `hrm_db`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`region` (
  `region` VARCHAR(255) NOT NULL,
  `country` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`region`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrm_db`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`city` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `region` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_city_region1_idx` (`region` ASC),
  CONSTRAINT `fk_city_region1`
    FOREIGN KEY (`region`)
    REFERENCES `hrm_db`.`region` (`region`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrm_db`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`address` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `line1` VARCHAR(255) NOT NULL,
  `line2` VARCHAR(255) NOT NULL,
  `city_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_city1_idx` (`city_id` ASC),
  CONSTRAINT `fk_address_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `hrm_db`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrm_db`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`branch` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address_id` INT(11) NOT NULL,
  `currency` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_branch_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_branch_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `hrm_db`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrm_db`.`custom_attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`custom_attribute` (
  `name` VARCHAR(255) NOT NULL,
  `type` ENUM('text', 'number') NOT NULL DEFAULT 'text',
  `default` VARCHAR(255) NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrm_db`.`employement_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`employement_type` (
  `type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`type`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrm_db`.`paygrade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`paygrade` (
  `name` VARCHAR(255) NOT NULL,
  `min_salary` DECIMAL(10,2) NOT NULL,
  `max_salary` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrm_db`.`job_title`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`job_title` (
  `title` VARCHAR(255) NOT NULL,
  `salary` DECIMAL(10,2) NOT NULL,
  `paygrade` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`title`),
  INDEX `fk_job_title_paygrade1_idx` (`paygrade` ASC),
  CONSTRAINT `fk_job_title_paygrade1`
    FOREIGN KEY (`paygrade`)
    REFERENCES `hrm_db`.`paygrade` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrm_db`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `budget` DECIMAL(10,2) NOT NULL,
  `branch_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_department_branch1_idx` (`branch_id` ASC),
  UNIQUE INDEX `unique_name_branch` (`name` ASC, `branch_id` ASC),
  CONSTRAINT `fk_department_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `hrm_db`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrm_db`.`employee_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`employee_record` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `middle_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `marital_status` VARCHAR(255) NOT NULL,
  `employment_type` VARCHAR(255) NOT NULL,
  `job_title` VARCHAR(255) NOT NULL,
  `supervisor_id` INT(11) NULL DEFAULT NULL,
  `birthdate` DATE NOT NULL,
  `employee_photo` VARCHAR(255) NULL DEFAULT NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_record_employement_type1_idx` (`employment_type` ASC),
  INDEX `fk_employee_record_job_title1_idx` (`job_title` ASC),
  INDEX `fk_employee_record_employee_record1_idx` (`supervisor_id` ASC),
  INDEX `fk_employee_record_department1_idx` (`department_id` ASC),
  CONSTRAINT `fk_employee_record_employee_record1`
    FOREIGN KEY (`supervisor_id`)
    REFERENCES `hrm_db`.`employee_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_record_employement_type1`
    FOREIGN KEY (`employment_type`)
    REFERENCES `hrm_db`.`employement_type` (`type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_record_job_title1`
    FOREIGN KEY (`job_title`)
    REFERENCES `hrm_db`.`job_title` (`title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_record_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `hrm_db`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrm_db`.`custom_attribute_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`custom_attribute_value` (
  `attribute_name` VARCHAR(255) NOT NULL,
  `employee_record_id` INT(11) NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`attribute_name`, `employee_record_id`, `value`),
  INDEX `fk_custom_attribute_value_employee_record1_idx` (`employee_record_id` ASC),
  INDEX `fk_custom_attribute_value_custom_attribute1_idx` (`attribute_name` ASC),
  CONSTRAINT `fk_custom_attribute_value_custom_attribute1`
    FOREIGN KEY (`attribute_name`)
    REFERENCES `hrm_db`.`custom_attribute` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_custom_attribute_value_employee_record1`
    FOREIGN KEY (`employee_record_id`)
    REFERENCES `hrm_db`.`employee_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrm_db`.`dependent_information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`dependent_information` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `employee_record_id` INT(11) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `middle_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `birthdate` DATE NOT NULL,
  `relation` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `employee_record_id`),
  UNIQUE INDEX `first_name_UNIQUE` (`first_name` ASC),
  UNIQUE INDEX `last_name_UNIQUE` (`last_name` ASC),
  UNIQUE INDEX `birthdate_UNIQUE` (`birthdate` ASC),
  UNIQUE INDEX `relation_UNIQUE` (`relation` ASC),
  INDEX `fk_dependent_information_employee_record1` (`employee_record_id` ASC),
  CONSTRAINT `fk_dependent_information_employee_record1`
    FOREIGN KEY (`employee_record_id`)
    REFERENCES `hrm_db`.`employee_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrm_db`.`employee_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`employee_account` (
  `employee_record_id` INT(11) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`employee_record_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_employee_account_employee_record_idx` (`employee_record_id` ASC),
  CONSTRAINT `fk_employee_account_employee_record`
    FOREIGN KEY (`employee_record_id`)
    REFERENCES `hrm_db`.`employee_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrm_db`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`role` (
  `role` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`role`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrm_db`.`employee_account_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`employee_account_has_role` (
  `employee_record_id` INT(11) NOT NULL,
  `role` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`employee_record_id`, `role`),
  INDEX `fk_employee_account_has_role_role1_idx` (`role` ASC),
  INDEX `fk_employee_account_has_role_employee_account1_idx` (`employee_record_id` ASC),
  CONSTRAINT `fk_employee_account_has_role_employee_account1`
    FOREIGN KEY (`employee_record_id`)
    REFERENCES `hrm_db`.`employee_account` (`employee_record_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_account_has_role_role1`
    FOREIGN KEY (`role`)
    REFERENCES `hrm_db`.`role` (`role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrm_db`.`job_title_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`job_title_has_role` (
  `job_title` VARCHAR(255) NOT NULL,
  `role` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`job_title`, `role`),
  INDEX `fk_job_title_has_role_role1_idx` (`role` ASC),
  INDEX `fk_job_title_has_role_job_title1_idx` (`job_title` ASC),
  CONSTRAINT `fk_job_title_has_role_job_title1`
    FOREIGN KEY (`job_title`)
    REFERENCES `hrm_db`.`job_title` (`title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_title_has_role_role1`
    FOREIGN KEY (`role`)
    REFERENCES `hrm_db`.`role` (`role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrm_db`.`absence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`absence` (
  `id` INT NOT NULL,
  `employee_record_id` INT(11) NOT NULL,
  `from` DATE NOT NULL,
  `to` DATE NOT NULL,
  `type` ENUM('annual', 'maternity', 'casual', 'nopay', 'uninformed') NOT NULL,
  `status` ENUM('taken', 'cancelled', 'approved', 'declined', 'pending') NOT NULL DEFAULT 'pending',
  `comment` TEXT NOT NULL,
  `approved_by` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_leave_employee_record1_idx` (`employee_record_id` ASC),
  INDEX `fk_absence_employee_record1_idx` (`approved_by` ASC),
  UNIQUE INDEX `unique_employee_from` (`employee_record_id` ASC, `from` ASC),
  CONSTRAINT `fk_leave_employee_record1`
    FOREIGN KEY (`employee_record_id`)
    REFERENCES `hrm_db`.`employee_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_absence_employee_record1`
    FOREIGN KEY (`approved_by`)
    REFERENCES `hrm_db`.`employee_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrm_db`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`organization` (
  `name` VARCHAR(255) NOT NULL,
  `registration_no` VARCHAR(255) NOT NULL,
  `root_branch_id` INT(11) NULL,
  PRIMARY KEY (`name`),
  INDEX `fk_organization_branch1_idx` (`root_branch_id` ASC),
  CONSTRAINT `fk_organization_branch1`
    FOREIGN KEY (`root_branch_id`)
    REFERENCES `hrm_db`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrm_db`.`paygrade_leave_limit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`paygrade_leave_limit` (
  `type` ENUM('annual', 'maternity', 'casual', 'nopay') NOT NULL DEFAULT 'nopay',
  `paygrade` VARCHAR(255) NOT NULL,
  `leave_count` INT(11) NOT NULL DEFAULT '50',
  `resets` ENUM('monthly', 'yearly') NOT NULL DEFAULT 'yearly',
  PRIMARY KEY (`type`, `paygrade`),
  INDEX `fk_paygrade_leave_limit_paygrade1_idx` (`paygrade` ASC),
  CONSTRAINT `fk_paygrade_leave_limit_paygrade1`
    FOREIGN KEY (`paygrade`)
    REFERENCES `hrm_db`.`paygrade` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrm_db`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`permission` (
  `entity` VARCHAR(255) NOT NULL,
  `action` ENUM('create', 'read', 'update', 'delete') NOT NULL,
  `group` ENUM('self', 'department', 'branch', 'all') NOT NULL,
  PRIMARY KEY (`entity`, `action`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrm_db`.`role_has_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`role_has_permission` (
  `role` VARCHAR(255) NOT NULL,
  `entity` VARCHAR(255) NOT NULL,
  `action` ENUM('create', 'read', 'update', 'delete') NOT NULL,
  PRIMARY KEY (`role`, `entity`, `action`),
  INDEX `fk_role_has_permission_role1_idx` (`role` ASC),
  INDEX `fk_Role has Permission_Permission1_idx` (`entity` ASC, `action` ASC),
  CONSTRAINT `fk_role_has_permission_role1`
    FOREIGN KEY (`role`)
    REFERENCES `hrm_db`.`role` (`role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Role has Permission_Permission1`
    FOREIGN KEY (`entity` , `action`)
    REFERENCES `hrm_db`.`permission` (`entity` , `action`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrm_db`.`employee_record_has_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`employee_record_has_address` (
  `employee_record_id` INT(11) NOT NULL,
  `address_id` INT(11) NOT NULL,
  PRIMARY KEY (`address_id`),
  INDEX `fk_employee_record_has_address_address1_idx` (`address_id` ASC),
  INDEX `fk_employee_record_has_address_employee_record1_idx` (`employee_record_id` ASC),
  CONSTRAINT `fk_employee_record_has_address_employee_record1`
    FOREIGN KEY (`employee_record_id`)
    REFERENCES `hrm_db`.`employee_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_record_has_address_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `hrm_db`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `rr` ;

-- -----------------------------------------------------
-- Table `rr`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rr`.`region` (
  `region` VARCHAR(255) NOT NULL,
  `country` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`region`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rr`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rr`.`city` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `region` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_city_region1_idx` (`region` ASC),
  CONSTRAINT `fk_city_region1`
    FOREIGN KEY (`region`)
    REFERENCES `rr`.`region` (`region`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rr`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rr`.`address` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `line1` VARCHAR(255) NOT NULL,
  `line2` VARCHAR(255) NOT NULL,
  `city_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_city1_idx` (`city_id` ASC),
  CONSTRAINT `fk_address_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `rr`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rr`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rr`.`branch` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address_id` INT(11) NOT NULL,
  `currency` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_branch_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_branch_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `rr`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rr`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rr`.`department` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `budget` DECIMAL(10,2) NOT NULL,
  `branch_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC, `branch_id` ASC),
  INDEX `fk_department_branch1_idx` (`branch_id` ASC),
  CONSTRAINT `fk_department_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `rr`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rr`.`employement_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rr`.`employement_type` (
  `type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`type`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rr`.`job_title`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rr`.`job_title` (
  `title` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`title`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rr`.`paygrade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rr`.`paygrade` (
  `name` VARCHAR(255) NOT NULL,
  `min_salary` DECIMAL(10,2) NOT NULL,
  `max_salary` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rr`.`employee_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rr`.`employee_record` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `middle_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `marital_status` VARCHAR(255) NOT NULL,
  `employment_type` VARCHAR(255) NOT NULL,
  `job_title` VARCHAR(255) NOT NULL,
  `paygrade` VARCHAR(255) NOT NULL,
  `supervisor_id` INT(11) NULL DEFAULT NULL,
  `address_id` INT(11) NOT NULL,
  `birthdate` DATE NOT NULL,
  `employee_photo` VARCHAR(255) NULL DEFAULT NULL,
  `salary` DECIMAL(10,2) NOT NULL,
  `department_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_record_employement_type1_idx` (`employment_type` ASC),
  INDEX `fk_employee_record_job_title1_idx` (`job_title` ASC),
  INDEX `fk_employee_record_paygrade1_idx` (`paygrade` ASC),
  INDEX `fk_employee_record_address1_idx` (`address_id` ASC),
  INDEX `fk_employee_record_employee_record1_idx` (`supervisor_id` ASC),
  INDEX `fk_employee_record_department1_idx` (`department_id` ASC),
  CONSTRAINT `fk_employee_record_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `rr`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_record_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `rr`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_record_employee_record1`
    FOREIGN KEY (`supervisor_id`)
    REFERENCES `rr`.`employee_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_record_employement_type1`
    FOREIGN KEY (`employment_type`)
    REFERENCES `rr`.`employement_type` (`type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_record_job_title1`
    FOREIGN KEY (`job_title`)
    REFERENCES `rr`.`job_title` (`title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_record_paygrade1`
    FOREIGN KEY (`paygrade`)
    REFERENCES `rr`.`paygrade` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rr`.`absence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rr`.`absence` (
  `id` INT(11) NOT NULL,
  `employee_record_id` INT(11) NOT NULL,
  `from` DATE NOT NULL,
  `to` DATE NOT NULL,
  `type` ENUM('annual', 'maternity', 'casual', 'nopay', 'uninformed') NOT NULL,
  `status` ENUM('taken', 'cancelled', 'approved', 'declined', 'pending') NOT NULL DEFAULT 'pending',
  `comment` TEXT NOT NULL,
  `supervisor_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `employee_record_id` USING BTREE (`employee_record_id` ASC, `from` ASC),
  INDEX `fk_leave_employee_record1_idx` (`employee_record_id` ASC),
  INDEX `fk_absence_employee_record1_idx` (`supervisor_id` ASC),
  CONSTRAINT `fk_absence_employee_record1`
    FOREIGN KEY (`supervisor_id`)
    REFERENCES `rr`.`employee_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_leave_employee_record1`
    FOREIGN KEY (`employee_record_id`)
    REFERENCES `rr`.`employee_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rr`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rr`.`country` (
  `idcountry` INT(11) NOT NULL,
  PRIMARY KEY (`idcountry`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rr`.`custom_attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rr`.`custom_attribute` (
  `name` VARCHAR(255) NOT NULL,
  `type` ENUM('text', 'number') NOT NULL DEFAULT 'text',
  `default` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rr`.`custom_attribute_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rr`.`custom_attribute_value` (
  `attribute_name` VARCHAR(255) NOT NULL,
  `employee_record_id` INT(11) NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`attribute_name`, `employee_record_id`, `value`),
  INDEX `fk_custom_attribute_value_employee_record1_idx` (`employee_record_id` ASC),
  INDEX `fk_custom_attribute_value_custom_attribute1_idx` (`attribute_name` ASC),
  CONSTRAINT `fk_custom_attribute_value_custom_attribute1`
    FOREIGN KEY (`attribute_name`)
    REFERENCES `rr`.`custom_attribute` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_custom_attribute_value_employee_record1`
    FOREIGN KEY (`employee_record_id`)
    REFERENCES `rr`.`employee_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rr`.`dependent_information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rr`.`dependent_information` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `employee_record_id` INT(11) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `middle_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `birthdate` DATE NOT NULL,
  `relation` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `employee_record_id`),
  UNIQUE INDEX `first_name_UNIQUE` (`first_name` ASC),
  UNIQUE INDEX `last_name_UNIQUE` (`last_name` ASC),
  UNIQUE INDEX `birthdate_UNIQUE` (`birthdate` ASC),
  UNIQUE INDEX `relation_UNIQUE` (`relation` ASC),
  INDEX `fk_dependent_information_employee_record1` (`employee_record_id` ASC),
  CONSTRAINT `fk_dependent_information_employee_record1`
    FOREIGN KEY (`employee_record_id`)
    REFERENCES `rr`.`employee_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rr`.`employee_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rr`.`employee_account` (
  `employee_record_id` INT(11) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`employee_record_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_employee_account_employee_record_idx` (`employee_record_id` ASC),
  CONSTRAINT `fk_employee_account_employee_record`
    FOREIGN KEY (`employee_record_id`)
    REFERENCES `rr`.`employee_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rr`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rr`.`role` (
  `role` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`role`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rr`.`employee_account_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rr`.`employee_account_has_role` (
  `employee_record_id` INT(11) NOT NULL,
  `role` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`employee_record_id`, `role`),
  INDEX `fk_employee_account_has_role_role1_idx` (`role` ASC),
  INDEX `fk_employee_account_has_role_employee_account1_idx` (`employee_record_id` ASC),
  CONSTRAINT `fk_employee_account_has_role_employee_account1`
    FOREIGN KEY (`employee_record_id`)
    REFERENCES `rr`.`employee_account` (`employee_record_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_account_has_role_role1`
    FOREIGN KEY (`role`)
    REFERENCES `rr`.`role` (`role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rr`.`job_title_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rr`.`job_title_has_role` (
  `job_title` VARCHAR(255) NOT NULL,
  `role` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`job_title`, `role`),
  INDEX `fk_job_title_has_role_role1_idx` (`role` ASC),
  INDEX `fk_job_title_has_role_job_title1_idx` (`job_title` ASC),
  CONSTRAINT `fk_job_title_has_role_job_title1`
    FOREIGN KEY (`job_title`)
    REFERENCES `rr`.`job_title` (`title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_title_has_role_role1`
    FOREIGN KEY (`role`)
    REFERENCES `rr`.`role` (`role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rr`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rr`.`organization` (
  `name` VARCHAR(255) NOT NULL,
  `registration_no` VARCHAR(255) NOT NULL,
  `root_branch_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`name`),
  INDEX `fk_organization_branch1_idx` (`root_branch_id` ASC),
  CONSTRAINT `fk_organization_branch1`
    FOREIGN KEY (`root_branch_id`)
    REFERENCES `rr`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rr`.`paygrade_leave_limit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rr`.`paygrade_leave_limit` (
  `type` ENUM('annual', 'maternity', 'casual', 'nopay') NOT NULL DEFAULT 'nopay',
  `paygrade` VARCHAR(255) NOT NULL,
  `leave_count` INT(11) NOT NULL DEFAULT '50',
  `resets` ENUM('monthly', 'yearly') NOT NULL DEFAULT 'yearly',
  PRIMARY KEY (`type`, `paygrade`),
  INDEX `fk_paygrade_leave_limit_paygrade1_idx` (`paygrade` ASC),
  CONSTRAINT `fk_paygrade_leave_limit_paygrade1`
    FOREIGN KEY (`paygrade`)
    REFERENCES `rr`.`paygrade` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rr`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rr`.`permission` (
  `entity` VARCHAR(255) NOT NULL,
  `action` ENUM('create', 'read', 'update', 'delete') NOT NULL,
  `group` ENUM('self', 'department', 'branch', 'all') NOT NULL,
  PRIMARY KEY (`entity`, `action`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rr`.`role_has_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rr`.`role_has_permission` (
  `role` VARCHAR(255) NOT NULL,
  `entity` VARCHAR(255) NOT NULL,
  `action` ENUM('create', 'read', 'update', 'delete') NOT NULL,
  PRIMARY KEY (`role`, `entity`, `action`),
  INDEX `fk_role_has_permission_role1_idx` (`role` ASC),
  INDEX `fk_Role has Permission_Permission1_idx` (`entity` ASC, `action` ASC),
  CONSTRAINT `fk_Role has Permission_Permission1`
    FOREIGN KEY (`entity` , `action`)
    REFERENCES `rr`.`permission` (`entity` , `action`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_permission_role1`
    FOREIGN KEY (`role`)
    REFERENCES `rr`.`role` (`role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `hrm_db` ;

-- -----------------------------------------------------
-- function add_address
-- -----------------------------------------------------

DELIMITER $$
USE `hrm_db`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `add_address`(`line1` VARCHAR(255), `line2` VARCHAR(255),`city` VARCHAR(255), `region` VARCHAR(255), `country` VARCHAR(255))
RETURNS INT
BEGIN
	SELECT `region`, `country` from `region` where `region`.`region` = lower(region) AND `region`.`country` = lower(country) INTO @region, @country;
    IF ISNULL(@region) OR ISNULL(@country) THEN
		INSERT INTO `region` (`region`, `country`) VALUES (lower(region), lower(country));
    END IF;
    
	SELECT 
    `id`
FROM
    `city`
WHERE
    `city`.`name` = LOWER(city)
        AND `city`.`region` = LOWER(region) INTO @city_id;
    If ISNULL(@city_id) THEN
		INSERT INTO `city` (`name`, `region`) VALUES (lower(city), lower(region));
        SET @city_id = LAST_INSERT_ID();
    END IF;
    INSERT INTO `address` (`line1`, `line2`, `city_id`) VALUES(line1, line2, @city_id);
    RETURN (LAST_INSERT_ID());
END$$

DELIMITER ;
USE `rr` ;

-- -----------------------------------------------------
-- function add_address
-- -----------------------------------------------------

DELIMITER $$
USE `rr`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `add_address`(`line1` VARCHAR(255), `line2` VARCHAR(255), `city` VARCHAR(255), `region` VARCHAR(255), `country` VARCHAR(255)) RETURNS int(11)
BEGIN
	SELECT `region`, `country` from `region` where `region`.`region` = lower(region) AND `region`.`country` = lower(country) INTO @region, @country;
    IF ISNULL(@region) OR ISNULL(@country) THEN
		INSERT INTO `region` (`region`, `country`) VALUES (lower(region), lower(country));
    END IF;
    
	SELECT 
    `id`
FROM
    `city`
WHERE
    `city`.`name` = LOWER(city)
        AND `city`.`region` = LOWER(region) INTO @city_id;
    If ISNULL(@city_id) THEN
		INSERT INTO `city` (`name`, `region`) VALUES (lower(city), lower(region));
        SET @city_id = LAST_INSERT_ID();
    END IF;
    INSERT INTO `address` (`line1`, `line2`, `city_id`) VALUES(line1, line2, @city_id);
    RETURN (LAST_INSERT_ID());
END$$

DELIMITER ;
USE `hrm_db`;

DELIMITER $$
USE `hrm_db`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `hrm_db`.`paygrade_chk_salary_is_valid_BEFORE_INSERT`
BEFORE INSERT ON `hrm_db`.`paygrade`
FOR EACH ROW
BEGIN
	IF NEW.min_salary <= 0 OR NEW.max_salary < NEW.min_salary THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = "Invalid values for min and max salaries";
    END IF;
END$$

USE `hrm_db`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `hrm_db`.`leave_check_date_validity_BEFORE_INSERT`
BEFORE INSERT ON `hrm_db`.`absence`
FOR EACH ROW
BEGIN
	IF NEW.from < NOW() OR NEW.from > NEW.to THEN
		SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = "To/From dates are not valid";
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
