-- MySQL Script generated by MySQL Workbench
-- 2019-12-02 14:34:57 +0530
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hrm_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hrm_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hrm_db` DEFAULT CHARACTER SET utf8 ;
USE `hrm_db` ;

-- -----------------------------------------------------
-- Table `hrm_db`.`employement_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`employement_type` (
  `type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`region` (
  `region` VARCHAR(255) NOT NULL,
  `country` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`region`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`city` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `region` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_city_region1_idx` (`region` ASC),
  CONSTRAINT `fk_city_region1`
    FOREIGN KEY (`region`)
    REFERENCES `hrm_db`.`region` (`region`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`address` (
  `id` INT NOT NULL,
  `line1` VARCHAR(255) NOT NULL,
  `line2` VARCHAR(255) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_city1_idx` (`city_id` ASC),
  CONSTRAINT `fk_address_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `hrm_db`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`branch` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_branch_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_branch_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `hrm_db`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`department` (
  `name` VARCHAR(255) NOT NULL,
  `budget` DECIMAL(10,2) NULL,
  `branch_id` INT NOT NULL,
  PRIMARY KEY (`name`, `branch_id`),
  INDEX `fk_department_branch1_idx` (`branch_id` ASC),
  CONSTRAINT `fk_department_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `hrm_db`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`job_title`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`job_title` (
  `title` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`title`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`paygrade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`paygrade` (
  `name` VARCHAR(255) NOT NULL,
  `salary` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`employee_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`employee_record` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `marital_status` VARCHAR(255) NOT NULL,
  `employement_type` VARCHAR(255) NOT NULL,
  `department` VARCHAR(255) NOT NULL,
  `job_title` VARCHAR(255) NOT NULL,
  `paygrade` VARCHAR(255) NOT NULL,
  `address_id` INT NOT NULL,
  `supervisor_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_record_employement_type1_idx` (`employement_type` ASC),
  INDEX `fk_employee_record_department1_idx` (`department` ASC),
  INDEX `fk_employee_record_job_title1_idx` (`job_title` ASC),
  INDEX `fk_employee_record_paygrade1_idx` (`paygrade` ASC),
  INDEX `fk_employee_record_address1_idx` (`address_id` ASC),
  INDEX `fk_employee_record_employee_record1_idx` (`supervisor_id` ASC),
  CONSTRAINT `fk_employee_record_employement_type1`
    FOREIGN KEY (`employement_type`)
    REFERENCES `hrm_db`.`employement_type` (`type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_record_department1`
    FOREIGN KEY (`department`)
    REFERENCES `hrm_db`.`department` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_record_job_title1`
    FOREIGN KEY (`job_title`)
    REFERENCES `hrm_db`.`job_title` (`title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_record_paygrade1`
    FOREIGN KEY (`paygrade`)
    REFERENCES `hrm_db`.`paygrade` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_record_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `hrm_db`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_record_employee_record1`
    FOREIGN KEY (`supervisor_id`)
    REFERENCES `hrm_db`.`employee_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`employee_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`employee_account` (
  `employee_record_id` INT NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  PRIMARY KEY (`employee_record_id`),
  INDEX `fk_employee_account_employee_record_idx` (`employee_record_id` ASC),
  CONSTRAINT `fk_employee_account_employee_record`
    FOREIGN KEY (`employee_record_id`)
    REFERENCES `hrm_db`.`employee_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`dependent_information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`dependent_information` (
  `employee_record_id` INT NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `birthdate` DATE NOT NULL,
  `relation` VARCHAR(255) NOT NULL,
  UNIQUE INDEX `first_name_UNIQUE` (`first_name` ASC),
  UNIQUE INDEX `last_name_UNIQUE` (`last_name` ASC),
  UNIQUE INDEX `birthdate_UNIQUE` (`birthdate` ASC),
  UNIQUE INDEX `relation_UNIQUE` (`relation` ASC),
  CONSTRAINT `fk_dependent_information_employee_record1`
    FOREIGN KEY (`employee_record_id`)
    REFERENCES `hrm_db`.`employee_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`organization` (
  `name` INT NOT NULL,
  `address` VARCHAR(255) NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`custom_attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`custom_attribute` (
  `name` VARCHAR(255) NOT NULL,
  `type` ENUM('text', 'select') NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`custom_attribute_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`custom_attribute_value` (
  `attribute_name` VARCHAR(255) NOT NULL,
  `employee_record_id` INT NOT NULL,
  `value` VARCHAR(255) NULL,
  PRIMARY KEY (`attribute_name`, `employee_record_id`, `value`),
  INDEX `fk_custom_attribute_value_employee_record1_idx` (`employee_record_id` ASC),
  INDEX `fk_custom_attribute_value_custom_attribute1_idx` (`attribute_name` ASC),
  CONSTRAINT `fk_custom_attribute_value_employee_record1`
    FOREIGN KEY (`employee_record_id`)
    REFERENCES `hrm_db`.`employee_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_custom_attribute_value_custom_attribute1`
    FOREIGN KEY (`attribute_name`)
    REFERENCES `hrm_db`.`custom_attribute` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`paygrade_leave_limit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`paygrade_leave_limit` (
  `type` ENUM('annual', 'maternity', 'casual', 'nopay') NOT NULL DEFAULT 'nopay',
  `paygrade` VARCHAR(255) NOT NULL,
  `leave_count` INT NOT NULL DEFAULT 50,
  `resets` ENUM('monthly', 'yearly') NOT NULL DEFAULT 'yearly',
  PRIMARY KEY (`type`, `paygrade`),
  INDEX `fk_paygrade_leave_limit_paygrade1_idx` (`paygrade` ASC),
  CONSTRAINT `fk_paygrade_leave_limit_paygrade1`
    FOREIGN KEY (`paygrade`)
    REFERENCES `hrm_db`.`paygrade` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`role` (
  `role` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`permission` (
  `permission` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`permission`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`role_has_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`role_has_permission` (
  `role` VARCHAR(255) NOT NULL,
  `permission` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`role`, `permission`),
  INDEX `fk_role_has_permission_permission1_idx` (`permission` ASC),
  INDEX `fk_role_has_permission_role1_idx` (`role` ASC),
  CONSTRAINT `fk_role_has_permission_role1`
    FOREIGN KEY (`role`)
    REFERENCES `hrm_db`.`role` (`role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_permission_permission1`
    FOREIGN KEY (`permission`)
    REFERENCES `hrm_db`.`permission` (`permission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`employee_account_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`employee_account_has_role` (
  `employee_record_id` INT NOT NULL,
  `role` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`employee_record_id`, `role`),
  INDEX `fk_employee_account_has_role_role1_idx` (`role` ASC),
  INDEX `fk_employee_account_has_role_employee_account1_idx` (`employee_record_id` ASC),
  CONSTRAINT `fk_employee_account_has_role_employee_account1`
    FOREIGN KEY (`employee_record_id`)
    REFERENCES `hrm_db`.`employee_account` (`employee_record_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_account_has_role_role1`
    FOREIGN KEY (`role`)
    REFERENCES `hrm_db`.`role` (`role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`job_title_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`job_title_has_role` (
  `job_title` VARCHAR(255) NOT NULL,
  `role` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`job_title`, `role`),
  INDEX `fk_job_title_has_role_role1_idx` (`role` ASC),
  INDEX `fk_job_title_has_role_job_title1_idx` (`job_title` ASC),
  CONSTRAINT `fk_job_title_has_role_job_title1`
    FOREIGN KEY (`job_title`)
    REFERENCES `hrm_db`.`job_title` (`title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_title_has_role_role1`
    FOREIGN KEY (`role`)
    REFERENCES `hrm_db`.`role` (`role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`leave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`leave` (
  `employee_record_id` INT NOT NULL,
  `from` DATE NOT NULL,
  `to` DATE NOT NULL,
  `type` ENUM('annual', 'maternity', 'casual', 'nopay') NOT NULL,
  `status` ENUM('approved', 'declined', 'pending') NOT NULL DEFAULT 'pending',
  PRIMARY KEY (`employee_record_id`, `from`),
  INDEX `fk_leave_employee_record1_idx` (`employee_record_id` ASC),
  CONSTRAINT `fk_leave_employee_record1`
    FOREIGN KEY (`employee_record_id`)
    REFERENCES `hrm_db`.`employee_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`taken_leaves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`taken_leaves` (
  `employee_record_id` INT NOT NULL,
  `type` ENUM('annual', 'maternity', 'casual', 'nopay') NOT NULL,
  `value` INT NOT NULL,
  PRIMARY KEY (`employee_record_id`, `type`),
  INDEX `fk_taken_leaves_employee_record1_idx` (`employee_record_id` ASC),
  CONSTRAINT `fk_taken_leaves_employee_record1`
    FOREIGN KEY (`employee_record_id`)
    REFERENCES `hrm_db`.`employee_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`region` (
  `region` VARCHAR(255) NOT NULL,
  `country` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`region`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrm_db`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hrm_db`.`country` (
  `idcountry` INT NOT NULL,
  PRIMARY KEY (`idcountry`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
